---
- hosts: linuxservers
  become: yes
  vars_files:
    - ~/secret.yml
    
  tasks:
  - name: Create file
    file:
      path: /root/testfile.txt
      state: touch

  - name: Add line in file
    lineinfile:
      path: /root/testfile.txt
      line: Ansible was here...